### ISSUE TITLE
ArgumentError: wrong number of arguments (given 2, expected 1)

### ISSUE THREAD

**Issue by benjaminoakes** [benjaminoakes/maid#175]
This spec is failing on Ruby 2.3.8 and above.  Help is appreciated!

```
  1) Maid::Tools#find returns an array of all the files' names when no block is given
     Failure/Error: expect(@maid.find(@dir)).to match_array([@dir_expand_path, @file_expand_path])
     ArgumentError:
       wrong number of arguments (given 2, expected 1)
     # ./vendor/bundle/ruby/2.3.0/gems/fakefs-0.4.3/lib/fakefs/dir.rb:83:in `entries'
     # ./lib/maid/tools.rb:335:in `each'
     # ./lib/maid/tools.rb:335:in `to_a'
     # ./lib/maid/tools.rb:335:in `find'
     # ./spec/lib/maid/tools_spec.rb:371:in `block (3 levels) in <module:Maid>'
```

**Comment by benjaminoakes** [comment]
Fixed in #177
