### ISSUE TITLE
incompatible character encodings

### ISSUE THREAD

**Issue by Canorus** [benjaminoakes/maid#178]
```
the-macbook-air:~ canor$ ruby --version
ruby 2.6.2p47 (2019-03-13 revision 67232) [x86_64-darwin18]
```

ruby was installed via hombrew

```
the-macbook-air:~ canor$ maid --version
0.7.0
```

This worked ok when run with crontab, but error occurs when I switched to launchd(unfortunately [jurriaan's blog](http://jurriaan.ninja/2015/01/01/maid-on-os-x.html) is down/certificate is out of date at the time of writing so I couldn't get help from there.)

```
/usr/local/lib/ruby/gems/2.6.0/gems/maid-0.7.0/lib/maid/tools.rb:785:in `expand_path': incompatible character encodings: UTF-8 and US-ASCII (Encoding::CompatibilityError)
        from /usr/local/lib/ruby/gems/2.6.0/gems/maid-0.7.0/lib/maid/tools.rb:785:in `expand'
        from /usr/local/lib/ruby/gems/2.6.0/gems/maid-0.7.0/lib/maid/tools.rb:789:in `block in expand_all'
        from /usr/local/lib/ruby/gems/2.6.0/gems/maid-0.7.0/lib/maid/tools.rb:789:in `map'
        from /usr/local/lib/ruby/gems/2.6.0/gems/maid-0.7.0/lib/maid/tools.rb:789:in `expand_all'
        from /usr/local/lib/ruby/gems/2.6.0/gems/maid-0.7.0/lib/maid/tools.rb:241:in `dir'
        from /Users/Canor/.maid/rules.rb:93:in `block (2 levels) in <top (required)>'
        from /usr/local/lib/ruby/gems/2.6.0/gems/maid-0.7.0/lib/maid/rule.rb:4:in `instance_exec'
        from /usr/local/lib/ruby/gems/2.6.0/gems/maid-0.7.0/lib/maid/rule.rb:4:in `follow'
        from /usr/local/lib/ruby/gems/2.6.0/gems/maid-0.7.0/lib/maid/rule_container.rb:20:in `block in follow_rules'
        from /usr/local/lib/ruby/gems/2.6.0/gems/maid-0.7.0/lib/maid/rule_container.rb:18:in `each'
        from /usr/local/lib/ruby/gems/2.6.0/gems/maid-0.7.0/lib/maid/rule_container.rb:18:in `follow_rules'
        from /usr/local/lib/ruby/gems/2.6.0/gems/maid-0.7.0/lib/maid/maid.rb:67:in `clean'
        from /usr/local/lib/ruby/gems/2.6.0/gems/maid-0.7.0/lib/maid/app.rb:51:in `clean'
        from /usr/local/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
        from /usr/local/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
        from /usr/local/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
        from /usr/local/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
        from /usr/local/lib/ruby/gems/2.6.0/gems/maid-0.7.0/bin/maid:5:in `<top (required)>'
        from /usr/local/bin/maid:23:in `load'
        from /usr/local/bin/maid:23:in `<main>'
```

and line 93 in rules.rb goes like this

```
    rule 'Move old screenshots to NAS' do
        dir('~/Pictures/screencapture/스크린샷*').each do |f|
                if 1.week.since(accessed_at(f))
                    up_to_NAS(f, '/volume1/homes/canor/myfiles/mac/screencapture/')
                end
         end
    end
```

CJK character there seems to be the problem but have no idea how to handle this.

**Comment by Plloi** [comment]
Looks like a text encoding issue... Can you post the output of `locale`?

**Comment by Canorus** [comment]
Here it is:

```
LANG="ko_KR.UTF-8"
LC_COLLATE="ko_KR.UTF-8"
LC_CTYPE="ko_KR.UTF-8"
LC_MESSAGES="ko_KR.UTF-8"
LC_MONETARY="ko_KR.UTF-8"
LC_NUMERIC="ko_KR.UTF-8"
LC_TIME="ko_KR.UTF-8"
LC_ALL=
```

thanks

**Comment by Plloi** [comment]
can you try replacing:

    dir('~/Pictures/screencapture/스크린샷*').each do |f|

with:

    dir('~/Pictures/screencapture/스크린샷*'.unicode_normalize ).each do |f|

**Comment by Canorus** [comment]
Sorry for the delay, I thought I already replied back.

Still same error logs with `.unicode_normalize`

**Comment by Canorus** [comment]
for my fellow Korean users who will find unicode issue like me:

normalize to `nfd`. 

```
dir('~/Pictures/screencapture/스크린샷*'.unicode_normalize(:nfd).each do |f|
```
