### ISSUE TITLE
maid doesn't work

### ISSUE THREAD

**Issue by alexriabtsev** [benjaminoakes/maid#179]
maid clean -f
Traceback (most recent call last):
	10: from /usr/local/bin/maid:6:in `<main>'
	 9: from /usr/local/bin/maid:6:in `load'
	 8: from /usr/local/Cellar/gem-maid/0.7.0/gems/maid-0.7.0/bin/maid:3:in `<top (required)>'
	 7: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 6: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 5: from /usr/local/Cellar/gem-maid/0.7.0/gems/maid-0.7.0/lib/maid.rb:16:in `<top (required)>'
	 4: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 3: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 2: from /usr/local/Cellar/gem-maid/0.7.0/gems/maid-0.7.0/lib/maid/rake/task.rb:1:in `<top (required)>'
	 1: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- rake (LoadError)

I'm new to Maid and doesn't understand what do these errors mean :(

**Comment by alexriabtsev** [comment]
macOS Catalina
Homebrew install

**Comment by alexriabtsev** [comment]
OK, I found out.
That's because I've installed via Homebrew.
After _gem install maid_ everything worked.
